let capital=[
{country: 'China', capital:'Pyongyang', answer:  false },
{country: 'Greece', capital:'Athens', answer:  true },
{country: 'Argentina', capital:'Dhaka', answer:  false },
{country: 'Myanmar', capital:'Naypyidaw', answer:  true },
{country: 'India', capital:'Stockholm', answer:  false },
{country: 'Palestine', capital:'Athens', answer:  false },
{country: 'Zimbabwe', capital:'Hanoi', answer:  false },
{country: 'Ecuador', capital:'Quito', answer:  true },
{country: 'South Africa', capital:'Pretoria', answer:  true },
{country: 'United Arab Emirates', capital:'Lisbon', answer:  false },
{country: 'Canada', capital:'Naypyidaw', answer:  false },
{country: 'Iceland', capital:'Abuja', answer:  false },
{country: 'Czech Republic', capital:'Prague', answer:  true },
{country: 'France', capital:'Paris', answer:  true },
{country: 'Vietnam', capital:'Hanoi', answer:  true },
{country: 'Belgium', capital:'Brussels', answer:  true },
{country: 'Indonesia', capital:'Thimphu', answer:  false },
{country: 'Luxembourg', capital:'Luxembourg', answer:  true },
{country: 'Denmark', capital:'Amsterdam', answer:  false },
{country: 'Chile', capital:'Edinburgh', answer:  false },
{country: 'Malaysia', capital:'Ottawa', answer:  false },
{country: 'Uzbekistan', capital:'Beijing', answer:  false },
{country: 'Paraguay', capital:'Asunción', answer:  true },
{country: 'Philippines', capital:'Muscat', answer:  false },
{country: 'Iraq', capital:'Seoul', answer:  false },
{country: 'Morocco', capital:'Rabat', answer:  true },
{country: 'Singapore', capital:'Edinburgh', answer:  false },
{country: 'Australia', capital:'Tokyo', answer:  false },
{country: 'New Zealand', capital:'Baghdad', answer:  false },
{country: 'Nepal', capital:'Kathmandu', answer:  true },
{country: 'Nigeria', capital:'Athens', answer:  false },
{country: 'Syria', capital:'Cardiff', answer:  false },
{country: 'Poland', capital:'Riyadh', answer:  false },
{country: 'Vietnam', capital:'Paris', answer:  false },
{country: 'Luxembourg', capital:'Rome', answer:  false },
{country: 'Saudi Arabia', capital:'Pyongyang', answer:  false },
{country: 'Sri Lanka', capital:'Helsinki', answer:  false },
{country: 'Italy', capital:'Rome', answer:  true },
{country: 'Romania', capital:'Dushanbe', answer:  false },
{country: 'Ecuador', capital:'Washington, D.C.', answer:  false },
{country: 'Turkey', capital:'Ankara', answer:  true },
{country: 'Chile', capital:'Santiago', answer:  true },
{country: 'Egypt', capital:'Cairo', answer:  true },
{country: 'Switzerland', capital:'Bern', answer:  true },
{country: 'Vatican City', capital:'Helsinki', answer:  false },
{country: 'Qatar', capital:'Seoul', answer:  false },
{country: 'Colombia', capital:'Bogotá', answer:  true },
{country: 'Iraq', capital:'Baghdad', answer:  true },
{country: 'Thailand', capital:'Bangkok', answer:  true },
{country: 'Azerbaijan', capital:'Baku', answer:  true },
{country: 'Thailand', capital:'Madrid', answer:  false },
{country: 'Kenya', capital:'Tashkent', answer:  false },
{country: 'France', capital:'Dushanbe', answer:  false },
{country: 'Singapore', capital:'Singapore', answer:  true },
{country: 'Wales', capital:'Cardiff', answer:  true },
{country: 'South Korea', capital:'Seoul', answer:  true },
{country: 'Kuwait', capital:'Wellington', answer:  false },
{country: 'Cuba', capital:'Havana', answer:  true },
{country: 'Israel', capital:'Jerusalem', answer:  true },
{country: 'United Kingdom; England', capital:'London', answer:  true },
{country: 'India', capital:'New Delhi', answer:  true },
{country: 'Mexico', capital:'Mexico City', answer:  true },
{country: 'Bangladesh', capital:'Singapore', answer:  false },
{country: 'United States', capital:'Washington, D.C.', answer:  true },
{country: 'Panama', capital:'Panama City', answer:  true },
{country: 'Iran', capital:'Kuala Lumpur', answer:  false },
{country: 'Denmark', capital:'Copenhagen', answer:  true },
{country: 'Spain', capital:'Dushanbe', answer:  false },
{country: 'Hungary', capital:'Santiago', answer:  false },
{country: 'Argentina', capital:'Buenos Aires', answer:  true },
{country: 'Germany', capital:'Bangkok', answer:  false },
{country: 'Israel', capital:'Nairobi', answer:  false },
{country: 'Germany', capital:'Berlin', answer:  true },
{country: 'Austria', capital:'Vienna', answer:  true },
{country: 'Japan', capital:'Islamabad', answer:  false },
{country: 'Norway', capital:'Oslo', answer:  true },
{country: 'Mexico', capital:'New Delhi', answer:  false },
{country: 'North Korea', capital:'Pyongyang', answer:  true },
{country: 'Greenland', capital:'Asunción', answer:  false },
{country: 'North Korea', capital:'Bern', answer:  false },
{country: 'China', capital:'Beijing', answer:  true },
{country: 'Nigeria', capital:'Abuja', answer:  true },
{country: 'Sri Lanka', capital:'Sri Jayawardenapura Kotte', answer:  true },
{country: 'United Arab Emirates', capital:'Abu Dhabi', answer:  true },
{country: 'Australia', capital:'Canberra', answer:  true },
{country: 'South Africa', capital:'Kuwait City', answer:  false },
{country: 'Oman', capital:'Muscat', answer:  true },
{country: 'South Korea', capital:'Stockholm', answer:  false },
{country: 'Kenya', capital:'Nairobi', answer:  true },
{country: 'Philippines', capital:'Manila', answer:  true },
{country: 'Finland', capital:'Brasília', answer:  false },
{country: 'Tajikistan', capital:'Dushanbe', answer:  true },
{country: 'Nepal', capital:'Beijing', answer:  false },
{country: 'Poland', capital:'Warsaw', answer:  true },
{country: 'Oman', capital:'Lisbon', answer:  false },
{country: 'Cuba', capital:'Baghdad', answer:  false },
{country: 'Colombia', capital:'Cardiff', answer:  false },
{country: 'Myanmar', capital:'London', answer:  false },
{country: 'Afghanistan', capital:'Kablu', answer:  true },
{country: 'Vatican City', capital:'Vatican City', answer:  true },
{country: 'Iran', capital:'Tehran', answer:  true },
{country: 'Portugal', capital:'Lisbon', answer:  true },
{country: 'Wales', capital:'Prague', answer:  false },
{country: 'Bangladesh', capital:'Dhaka', answer:  true },
{country: 'Maldives', capital:'Malé', answer:  true }
]

export default capital